### ISSUE TITLE
"No module named 'pages'" when importing module, to use with werkzeug DispatcherMiddleware.

### ISSUE THREAD

**Issue by vmatos** [plotly/dash-labs#91]
When I import my Dash application as a module, to be dispatched by werkzeug DispatcherMiddleware, I get the following error:

```
Traceback (most recent call last):
  File "dashboards.py", line 5, in <module>
    from app_one.app import app as one_app
  File "/home/vmatos/experiments/minimal_multipage_dispatcher/app_one/app.py", line 10, in <module>
    app = Dash(__name__, plugins=[dl.plugins.pages], requests_pathname_prefix=requests_pathname_prefix)
  File "/home/vmatos/experiments/minimal_multipage_dispatcher/venv/lib/python3.8/site-packages/dash/dash.py", line 458, in __init__
    plugin.plug(self)
  File "/home/vmatos/experiments/minimal_multipage_dispatcher/venv/lib/python3.8/site-packages/dash_labs/plugins/pages.py", line 321, in plug
    _import_layouts_from_pages(pages_folder)
  File "/home/vmatos/experiments/minimal_multipage_dispatcher/venv/lib/python3.8/site-packages/dash_labs/plugins/pages.py", line 295, in _import_layouts_from_pages
    page_module = importlib.import_module(f"pages.{page_filename}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'pages'
```

You can find a minimal replication of the issue in the repository: https://github.com/vmatos/minimal_multipage_dispatcher

**Comment by AnnMarieW** [comment]
@vmatos 
>But I find myself with each Dash instantiation deleting the previous pages registries.
Could you try using unique names in `dash.register_page()`, for example in app1:
```
dash.register_page("another_home1", layout=html.Div("App 1!"), path="/")
```

**Comment by AnnMarieW** [comment]
I looked into this a little more, and I expect that `pages` is not compatible with this method.  I'll confirm this with the Plotly team and see if they can suggest a work-around. 

It may be necessary to use the current pattern for multi-page apps described in the docs [Multi-page Apps and URL Support](https://dash.plotly.com/urls)

**Comment by IcToxi** [comment]
@AnnMarieW https://github.com/conda-forge/dash-labs-feedstock/pull/8
